package com.napzak.market.mixpanel

object MixpanelConstants {
    // Event Name
    const val COMPLETED_ONBOARDING = "Completed Onboarding"
    const val SIGNED_UP = "Signed Up"
    const val SKIPPED_GENRES = "Skipped Genres"
    const val CLICKED_CUSTOM_GENRE = "Clicked custom genre"
    const val CLICKED_BANNER = "Clicked Banner"
    const val VIEWED_POPULAR_SALE = "Viewed Popular For Sale"
    const val VIEWED_POPULAR_WANTED = "Viewed Popular Wanted"
    const val OPENED_SEARCH = "Opened Search"
    const val EXECUTED_SEARCH = "Executed Search"
    const val CLICKED_SUGGESTION = "Clicked Suggestion"
    const val VIEWED_EXPLORE = "Viewed Explore"
    const val APPLIED_GENRE_FILTER = "Applied Genre Filter"
    const val APPLIED_ARRAY_FILTER = "Applied array Filter"
    const val VIEWED_PRODUCT = "Viewed Product"
    const val STARTED_CHAT = "Started Chat"
    const val CREATED_POST = "Created Post"
    const val VIEWED_MYPAGE = "Viewed MyPage"
    const val VIEWED_SETTING = "Viewed Settings"
    const val TOGGLED_ALARM = "Toggled Alarm"
    const val LOGGED_OUT = "Logged Out"
    const val STARTED_WITHDRAWAL = "Started Withdrawal"
    const val COMPLETED_WITHDRAWAL = "Completed Withdrawal"
    const val OPENED_REPORT_PRODUCT = "Opened Report Overlay_product"
    const val OPENED_REPORT_MARKET = "Opened Report Overlay_market"
    const val CHANGED_PRODUCT_STATUS = "Changed Product_status"

    // Property Keys
    const val METHOD = "method"
    const val PLATFORM = "platform"
    const val GENRES_COUNT = "genres_selected_count"
    const val GENRES_CATEGORY = "genres_category"
    const val ITEM_INDEX = "item_index"
    const val BANNER_ID = "banner_id"
    const val BANNER_TYPE = "banner_type"
    const val BANNER_INDEX = "banner_index"
    const val SEARCH_SOURCE = "search_source"
    const val SEARCH_TEXT = "keyword"
    const val SUGGESTION_TYPE = "suggestion_type"
    const val SUGGESTION_INDEX = "suggestion_index"
    const val TAB = "tab"
    const val FILTER_COUNT = "filter_count"
    const val SORT = "sort"
    const val POST_ID = "post_id"
    const val POST_TYPE = "post_type"
    const val USER_ROLE = "user_role"
    const val STATUS = "status"
    const val PRODUCT_STATUS = "product_status"

    // Property Values
    const val KAKAO = "kakao"
    const val ANDROID = "android"
    const val BANNER_MAIN = "main"
    const val BANNER_MINI = "mini"
    const val ICON = "icon"
    const val SEARCH_BAR = "search_bar"
    const val GENRE_PAGE = "genre_page"
    const val ENTER = "enter"
    const val KEYWORD = "keyword"
    const val GENRE = "genre"
    const val FOR_SALE = "for_sale"
    const val WANTED = "wanted"
    const val LATEST = "latest"
    const val POPULAR = "popular"
    const val HIGH_PRICE = "high_price"
    const val LOW_PRICE = "low_price"
    const val BUYER = "buyer"
    const val SELLER = "seller"
    const val ON = "on"
    const val OFF = "off"
    const val IN_PROGRESS = "in_progress"
    const val PAYMENT_COMPLETED = "payment_completed"
    const val SALE_COMPLETED = "sale_completed"
}
