package com.napzak.market.mixpanel

object MixpanelConstants {
    const val COMPLETED_ONBOARDING = "Completed Onboarding"
    const val SIGNED_UP = "Signed Up"
    const val SKIPPED_GENRES = "Skipped Genres"
    const val CLICKED_CUSTOM_GENRE = "Clicked custom genre"
    const val CLICKED_BANNER = "Clicked Banner"
    const val VIEWED_POPULAR_SALE = "Viewed Popular For Sale"
    const val VIEWED_POPULAR_WANTED = "Viewed Popular Wanted"
    const val OPENED_SEARCH = "Opened Search"
    const val EXECUTED_SEARCH = "Executed Search"
    const val CLICKED_SUGGESTION = "Clicked Suggestion"
    const val VIEWED_EXPLORE = "Viewed Explore"
    const val APPLIED_GENRE_FILTER = "Applied Genre Filter"
    const val APPLIED_ARRAY_FILTER = "Applied array Filter"
    const val VIEWED_PRODUCT = "Viewed Product"
    const val STARTED_CHAT = "Started Chat"
    const val CREATED_POST = "Created Post"
    const val VIEWED_MYPAGE = "Viewed MyPage"
    const val VIEWED_SETTING = "Viewed Settings"
    const val TOGGLED_ALARM = "Toggled Alarm"
    const val LOGGED_OUT = "Logged Out"
    const val STARTED_WITHDRAWAL = "Started Withdrawal"
    const val COMPLETED_WITHDRAWAL = "Completed Withdrawal"
    const val OPENED_REPORT_PRODUCT = "Opened Report Overlay_product"
    const val OPENED_REPORT_MARKET = "Opened Report Overlay_market"
    const val ITEM_STATUS_UPDATED = "Item Status Updated"
    const val ITEM_LIKED = "Item Liked"
}
