package com.napzak.market.market.model

data class Product( // TODO: 추후 domain으로 이동 예정
    val id: Long,
    val name: String,
    val genre: String,
    val photo: String,
    val price: Int,
    val uploadTime: String,
    val isInterested: Boolean,
    val tradeType: String,
    val tradeStatus: String,
    val isPriceNegotiable: Boolean = false, // "구해요"에만 사용
    val isOwnedByCurrentUser: Boolean = false,
    val likeCount: Int,
    val reviewCount: Int,
) {
    companion object {
        val mockMixedProduct = listOf(
            Product(
                id = 1,
                name = "은혼 긴토키 하지카타 룩업",
                genre = "은혼",
                photo = "",
                price = 125000,
                uploadTime = "1일 전",
                isInterested = false,
                tradeType = "SELL",
                tradeStatus = "BEFORE_TRADE",
                isPriceNegotiable = false,
                isOwnedByCurrentUser = false,
                likeCount = 10,
                reviewCount = 10,
            ),
            Product(
                id = 2,
                name = "은혼 긴토키 하지카타 룩업",
                genre = "은혼",
                photo = "",
                price = 125000,
                uploadTime = "1일 전",
                isInterested = false,
                tradeType = "BUY",
                tradeStatus = "BEFORE_TRADE",
                isPriceNegotiable = false,
                isOwnedByCurrentUser = false,
                likeCount = 10,
                reviewCount = 10,
            ),
            Product(
                id = 3,
                name = "은혼 긴토키 하지카타 룩업",
                genre = "은혼",
                photo = "",
                price = 125000,
                uploadTime = "1일 전",
                isInterested = false,
                tradeType = "SELL",
                tradeStatus = "BEFORE_TRADE",
                isPriceNegotiable = false,
                isOwnedByCurrentUser = false,
                likeCount = 10,
                reviewCount = 10,
            ),
            Product(
                id = 4,
                name = "은혼 긴토키 하지카타 룩업",
                genre = "은혼",
                photo = "",
                price = 125000,
                uploadTime = "1일 전",
                isInterested = false,
                tradeType = "BUY",
                tradeStatus = "BEFORE_TRADE",
                isPriceNegotiable = false,
                isOwnedByCurrentUser = false,
                likeCount = 10,
                reviewCount = 10,
            ),
            Product(
                id = 5,
                name = "은혼 긴토키 하지카타 룩업",
                genre = "은혼",
                photo = "",
                price = 125000,
                uploadTime = "1일 전",
                isInterested = false,
                tradeType = "SELL",
                tradeStatus = "BEFORE_TRADE",
                isPriceNegotiable = false,
                isOwnedByCurrentUser = false,
                likeCount = 10,
                reviewCount = 10,
            ),
            Product(
                id = 6,
                name = "은혼 긴토키 하지카타 룩업",
                genre = "은혼",
                photo = "",
                price = 125000,
                uploadTime = "1일 전",
                isInterested = false,
                tradeType = "BUY",
                tradeStatus = "BEFORE_TRADE",
                isPriceNegotiable = false,
                isOwnedByCurrentUser = false,
                likeCount = 10,
                reviewCount = 10,
            )
        )
    }
}