name: Napzak Release CD

# Fastlane을 활용해 Google Play Console에 배포를 진행합니다.
#

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

concurrency:
  group: release/*
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NAPZAK_RELEASE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create google-services.json
        run: |
          mkdir -p ./app/src/release
          echo '${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}' | base64 -d > ./app/src/release/google-services.json

      - name: Create local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Create signing files
        run: |
          mkdir -p ./app/signing
          echo '${{ secrets.NAPZAK_KEYSTORE_JKS }}' | base64 -d > ./app/signing/napzak-keystore.jks
          echo '${{ secrets.KEYSTORE_PROPERTIES }}' > ./app/signing/keystore.properties
          echo '${{ secrets.PLAY_STORE_KEY_JSON }}' > ./app/signing/play-store-key.json

      - name: Run fastlane deploy
        run: bundle exec fastlane deploy